name: learn-github-actions
on: [push]
jobs:
  build:
Â Â   runs-on: ubuntu-latest
Â Â Â  steps:
Â Â Â Â Â  - uses: actions/checkout@v2
Â Â Â Â Â  - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
