name: Telerik-Github-Actions-Practice

on: [push]
jobs:
Â  build:
Â Â Â  runs-on: ubuntu-latest
Â Â Â  steps:
Â Â Â  - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
Â Â Â  - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
Â Â Â  - name: Check out repository code
Â Â Â Â Â  uses: actions/checkout@v2
Â Â Â  - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
Â Â Â  - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
Â Â Â  - name: Set up Python 3.9
Â Â Â Â Â  uses: actions/setup-python@v2
Â Â Â Â Â  with:
Â Â Â Â Â Â Â  python-version: 3.9
Â Â Â  - name: Install dependencies
Â Â Â Â Â  run: |
Â Â Â Â Â Â Â  python -m pip install --upgrade pip
Â Â Â Â Â Â Â  pip install pylint
Â Â Â  - name: Lint with pylint
Â Â Â Â Â  run: |
Â Â Â Â Â Â Â  python lint_test.py
Â Â Â  - name: Build Container Image
Â Â Â Â Â  run: |
Â Â Â Â Â Â Â  echo "Building a container image..."
Â Â Â Â Â Â Â  sleep 60
Â Â Â Â Â Â Â  echo "Container built successfully!"
Â Â Â  - name: Deploy to cluster
Â Â Â Â Â  run: |
Â Â Â Â Â Â Â  echo "Deploying to web cluster using rolling deployment..."
Â Â Â Â Â Â Â  sleep 60
Â Â Â Â Â Â Â  echo "ğŸ‰ App has been deployed successfully!"
Â Â Â  - run: echo "This job's status is ${{ job.status }}."
